import { chromium, expect } from '@playwright/test';
import { testVrm } from '../tests/fixtures';
const origin = process.argv[2] ?? 'http://127.0.0.1:5180';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors: string[] = [], requests: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('request', request => requests.push(request.url()));
  await page.goto(origin + '/');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('好きな姿で');
  expect(await page.locator('.hero-visual img').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBeTruthy();
  await page.screenshot({ path: 'test-results/homepage-desktop.png', fullPage: true });
  await page.getByText('読み込んだファイルは公開されますか？').click();
  await expect(page.locator('#privacy')).toHaveAttribute('open', '');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await page.screenshot({ path: 'test-results/homepage-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'ルームを体験する', exact: false }).click();
  await expect(page).toHaveURL(origin + '/room/');
  await expect(page.locator('#status-text')).toHaveText('探索中 · この端末のみ', { timeout: 30000 });
  await expect(page.locator('#loading')).toBeHidden();
  await expect(page.locator('#avatar-name')).toHaveText('旅人');
  await page.locator('canvas').focus();
  await expect(page.locator('#coordinates')).toContainText('Z 2.4');
  await page.keyboard.down('KeyW'); await page.waitForTimeout(800); await page.keyboard.up('KeyW');
  await expect(page.locator('#coordinates')).not.toContainText('Z 2.4');
  await page.locator('#avatar-file').setInputFiles({ name: 'public-test.vrm', mimeType: 'application/octet-stream', buffer: Buffer.from(testVrm()) });
  await expect(page.locator('#avatar-name')).toHaveText('public-test', { timeout: 20000 });
  await page.locator('canvas').focus(); await page.keyboard.down('KeyD');
  await expect(page.locator('#viewport')).toHaveAttribute('data-motion', 'walk', { timeout: 10000 });
  await page.keyboard.up('KeyD');
  expect(requests.some(url => /avatars[\/]|\.vrm(?:[?#]|$)|vroid-files|local-avatar/.test(url))).toBe(false);
  expect(requests.filter(url => !url.startsWith(origin) && !url.startsWith('blob:'))).toEqual([]);
  await page.getByRole('link', { name: 'OpenVRoom 公式ホームページ' }).click();
  await expect(page).toHaveURL(origin + '/');
  expect(errors).toEqual([]);
  console.log(`PASS: ${origin} homepage desktop/mobile, /room/ navigation, standard avatar, VRM upload and walking, no private/outbound asset requests`);
} finally { await browser.close(); }
